### ISSUE TITLE
support centos7

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burpui_server#4]
centos7 isn't tested yet, add support and automatic tests

**Comment by mgrkisiek** [comment]
Hi 
Here are few things to correct 
nginx config need to /etc/nginx/conf.d with name burpui.conf 

gunicorn /etc/gunicorn doesn't exists -> to be removed 
gunicorn starting  script nice to put in /etc/systemd/system as gunicorn.service or burpui service . 
file should contait such data 
`
[Unit]
Description=Burp-UI gunicorn service
After=network.target

[Service]
User=root
Group=root
ExecStart=/usr/bin/gunicorn -c /etc/burp/burpui_gunicorn.py 'burpui:create_app(conf="/etc/burp/burpui.cfg",logfile="/var/log/gunicorn/burp-ui_info.log")'

[Install]
WantedBy=multi-user.target

`
Also file /etc/burp/burpui_gunicorn.py need to be upload with such content 
www.kisiek.net/burpui_gunicorn.py ( can't attache it ) 

Python  3 is not standart package in EL 7 ( always use pip2 ) :)

**Comment by pablodav** [comment]
Thanks you, I'm working on it. 

Hope to have it done in next days so I can help you fix your installation issues too.

**Comment by pablodav** [comment]
I have completed the support!
now creating new version!
