### ISSUE TITLE
Fedora installation problem

### ISSUE THREAD

**Issue by MrSuicideParrot** [CoffeeITWorks/ansible_burpui_server#7]
On the task RedHat.yml, the installation of the ius package is made to any OS from the RedHat family, but Fedora is from the RedHat family, but this package does not exist to Fedora.
The solution is to exclude the Fedora from this installation in the following way:
``` when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora' ```

**Comment by pablodav** [comment]
Thank you, I'm testing it.
